### ISSUE TITLE
What means of kafka_consumergroup_current_offset is -1

### ISSUE THREAD

**Issue by esstraty** [danielqsj/kafka_exporter#23]
As title ..

**Comment by jbkc85** [comment]
generally this means the consumer group of a given topic has no offsets.  -1 is really a '0' or a 'null' from my understanding.

**Comment by danielqsj** [comment]
@esstraty Pls refer to https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetFetchRequest: `Note that if there is no offset associated with a topic-partition under that consumer group the broker does not set an error code (since it is not really an error), but returns empty metadata and sets the offset field to -1.`
@jbkc85 Thanks.
