### ISSUE TITLE
cannot get consumer group lag

### ISSUE THREAD

**Issue by guoming** [danielqsj/kafka_exporter#237]
time="2021-06-26T03:40:03Z" level=error msg="No offset of topic canal_dwh2.gc_fps_receivable.account_flow_all partition 6, cannot get consumer group lag" source="kafka_exporter.go:473"

**Comment by changquanyou** [comment]
应该是没有监测到活跃的消费线程，我的现象是部分 Topic Lag 可以检测到，但是 Flink 相关的 Topic就无法监测到，查看 Topic 元信息， 没有看到活跃的消费线程

**Comment by Frank-Xie-SmartNews** [comment]
Hi,
  I also encounter similar issue. I use strimzi as kafka operator and launch exporter function(which use this exporter as default), some topics lag could be collected, but those topic which consumed by flink can't collect the lag metrics, I guess the reason is that flink use assign instead of subscribe, so the situation "Consumer group xxx has no active number" would happen and (CONSUMER-ID, HOST, CLIENT-ID) would be null, then when these two broker.DescribeGroups() && broker.FetchOffset() method were called and through error(broker not connected), so what should do to resolve this issue, thx

**Comment by danielqsj** [comment]
V1.4.0 is released, the default behavior of consumer group offset is same as v1.3.0, please have a try.
